### ISSUE TITLE
Undefined function or variable 'my_normc'.

### ISSUE THREAD

**Issue by patricegaofei** [vitorsr/SIHR#12]
Dear Prof. Vítor Ramos,

Thank you very much for the wonderful method implementations. 
Actually, I am stuck with the following error while trying to run Akashi2016.

Undefined function or variable 'my_normc'.
Error in Akashi2016 (line 36)
W_d = my_normc(W_d); % W_d ./ vecnorm(W_d, 2, 1); % normalize(W_d,1,'norm');

I have added a normalization function as follows.

`function N = my_normc(im, type, meth)
   meth = 'norm';
 type = 1;
 N = normalize(im, meth, type);
 end`

However, the restored images are very bad with high level of nois. Please, how should I solve this?
Any suggestions would be highly appreciated

**Comment by vitorsr** [comment]
Hello Patrice,

> the restored images are very bad with high level of nois. Please, how should I solve this?

Akashi and Okatani's method is prone to noise due to random initialization. In their paper, they run their algorithm a certain number of times and select the best tentative result out of those runs.

Since a single run takes 2 minutes (at least on my laptop), I did not implement this heuristic nor the selection of best _R_ (number of diffuse colors plus one). Instead, I do it manually on a per-use basis.

**Comment by patricegaofei** [comment]
Thank you for your reply! 
Please, is my normalization function correct? I thought the problem might be from that. Actually, the specular reflections are not even concealed. Instead, the images are just filled with noise.
