### ISSUE TITLE
More codes

### ISSUE THREAD

**Issue by fu123456** [vitorsr/SIHR#2]
Hi,
Very thank your work. Do you have the Matlab code of the article:
J. Guo, Z. Zhou, and L. Wang, “Single Image Highlight Removal with a Sparse and Low-Rank Reflection Model,” in Computer Vision – ECCV 2018, Springer International Publishing, 2018, pp. 282–298 [Online]. Available: http://dx.doi.org/10.1007/978-3-030-01225-0_17.
I need the code of this paper. Very thank you.

**Comment by vitorsr** [comment]
Hello @fu123456, this isn't a repository for official codebase for these articles - these are implementations made by me for these papers, since, like you, I did not find any code for them.

That said, I did read Guo's paper and emailed the authors some time ago. They did not respond.

Are you keen to try a hand at implement it? It does not seem to be awfully complicated, we can help eachother.

**Comment by vitorsr** [comment]
Have you considered what I said, @fu123456?

**Comment by fu123456** [comment]
Ok. That's fine.

**Comment by fu123456** [comment]
My email is xyzgfu@gmail.com. Please feel free to contact me for some issues. I also want to implement this paper.
