### ISSUE TITLE
Working of Tan, yang and Choudhury et al. 

### ISSUE THREAD

**Issue by Atif-Anwer** [vitorsr/SIHR#5]
Hi! 
Firstly, this is a great repository you have compiled and I really appreciate your effort in matlab implementations. They are of great help to get started on the area. 

While running the codes, I could not find a method to run the following codes:
- Tan et al 2005
- Choudhury et al 2005
- Yang et al 2010 

There are reference to variable 'src' but it is not the imread variable; unless I am missing something. Can you please guide on how to run these implementations? Any examples would be great. 
Thanks.

**Comment by vitorsr** [comment]
Hello Atif,

I agree it's a bit confusing right now - but it's because originally I did a "literal translation" of the original codes to MATLAB. I will change it soon in a future commit to make it simpler.

So, as of right now (state of current commit in master branch of this repo, vitorsr/SIHR):  
1) Tan's main function call is `[src,sfi,diff] = z.zHighlightRemoval(fname)`, where `fname` is the complete filename with path to the image, and `[src,sfi,diff]` are double-valued source, pseudo specular-free and diffuse output images.  
2) Yang's is `dst = qx_highlight_removal_bf(src)`, both double-valued images.  
3) I did not implement the trilateral filter (assuming that's what you mean by Choudhury 2005), don't know how can I help you with that since it's outside the scope of this repo.

**Comment by Atif-Anwer** [comment]
Thanks for the replies. Got both Tan and yang's code running now. 
Also, I saw the link to the trilateral implementation in the readme; which initially I had assumed it was related to specular highlights, which was an oversight on my part. 
I hope to be looking more into these papers and if I am able to update them, I will gladly submit them for a merge here. Thanks again for compiling this repo!

**Comment by vitorsr** [comment]
Thank you. I am a bit busy this semester so I'm not able to devote much time to add or implement more codes. Any help is appreciated.
